/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  aws_project_region: "sa-east-1",
  aws_cognito_identity_pool_id:
    "sa-east-1:621f8f51-0506-4df8-9f16-5829f47b30cb",
  aws_cognito_region: "sa-east-1",
  aws_user_pools_id: "sa-east-1_nZFmt9ofh",
  aws_user_pools_web_client_id: "4lpik9m5kh2sv5k2v8gbllr5uh",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsConfig;
